spring.application.name=basicauth
logging.level.root=ERROR
logging.level.org.springframework.boot.tomcat=INFO
logging.level.org.springframework.boot.security=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

jwt.secret=d72962b972860b4870f17a8750d8e3d2692cf61fbf349aa45badb57cdaf3690e