spring.application.name=basicauth
logging.level.root=ERROR
logging.level.org.springframework.boot.tomcat=INFO
logging.level.org.springframework.boot.security=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

jwt.secret=4189210c5435a6591d3ab60dfe328020dcd742e6c31abdea81e1216a0115f054

frontend.url=http://localhost:4200/
